### ISSUE TITLE
WinUI3 example: doesn't refresh

### ISSUE THREAD

**Issue by adrianhall** [CommunityToolkit/Datasync#156]
Reported by @trydalch

The WinUI3 (and potentially the WPF) version of the TodoApp does not refresh properly.

**Comment by trydalch** [comment]
I believe it's just the WinUI, and the issue is related to the bindings. The underlying data is correct, but the UI isn't updated. 

I actually added a fix in my PR for the initial Uno Sample (I'm discovering it may need more work for other platforms like iOS and Android) because Uno uses WinUI when targeting windows, so it had the same problem as the WinUI sample app. I fixed it for both WinUI and Uno. 

See: #137

**Comment by adrianhall** [comment]
Got it - I'm not actually seeing that, but I believe you; especially the sorting issue.  I'll check in the fixes for the WinUI3 change soon.  

Please remove the WinUI3 and WPF fixes from your PR - let's keep it focused on just the Uno sample.
