### ISSUE TITLE
README all NuGet Packages are invalid

### ISSUE THREAD

**Issue by JustAnotherLars** [CommunityToolkit/Datasync#52]
As the title says. Unfortunately, all NuGet package links are invalid.
Unfortunately, the packages cannot be found using NuGet either. 

https://github.com/CommunityToolkit/Datasync?tab=readme-ov-file#-nuget-packages

**Comment by adrianhall** [comment]
This repository is still under construction.  I appreciate the comments, but we aren’t there yet!

**Comment by Alexgoon** [comment]
@adrianhall  thanks for all your hard work in reviving the Azure Mobile Apps project! Just to confirm, is the first release set for September 2nd?

**Comment by adrianhall** [comment]
It’s a target - to be honest, looking unlikely at this point.  It’s one of these “it will be ready when it’s ready”.

**Comment by Alexgoon** [comment]
Thanks for the clarification! I'm really looking forward to the release since I want to include a topic on client-server data sync in my book about .NET MAUI :)

**Comment by adrianhall** [comment]
I look forward to it!

**Comment by Alexgoon** [comment]
@adrianhall Not sure if this thread is the right place to talk about it, but I’ve drafted a chapter for my .NET MAUI book that covers the Datasync library. Would you like to take a look? Since the library's documentation is still in progress, I wanted to make sure that I didn't make any mistakes. Your feedback would be really helpful.

Text: [Chapter6 - Recipe7.docx](https://github.com/user-attachments/files/17147015/Chapter6.-.Recipe7.docx)
Source code: [c6-OfflineDataSync](https://github.com/PacktPublishing/.NET-MAUI-Cookbook/tree/main/Chapter06/c6-OfflineDataSync)
